cp -r ~/.zshrc ~/git/dotfiles
cp -r ~/.config/termite ~/git/dotfiles/config
cp -r ~/.config/ranger ~/git/dotfiles/config
cp -r ~/.config/rofi ~/git/dotfiles/config
cp -r ~/.config/compton ~/git/dotfiles/config
cp -r ~/.config/picom ~/git/dotfiles/config
cp -r ~/.config/i3 ~/git/dotfiles/config
cp -r ~/.config/dunst ~/git/dotfiles/config
cp -r ~/.config/polybar ~/git/dotfiles/config
cp -r ~/.config/scripts ~/git/dotfiles/config
