#!/bin/bash

## Created By Aditya Shakya

MENU="$(rofi -sep "|" -dmenu -i -p 'Command' -width 12 -hide-scrollbar -line-padding 4 -padding 20 -lines 4 -theme oxide <<< " Lock| Logout| Reboot| Shutdown")"
            case "$MENU" in
                *Lock) i3lock-fancy ;;
                *Logout) openbox --exit;;
                *Reboot) systemctl reboot ;;
                *Shutdown) systemctl -i poweroff;;
            esac
